### ISSUE TITLE
Attempt to index a nil value - Crash

### ISSUE THREAD

**Issue by mmineweaser** [Spike2D/SimpleLog#16]
Attempt to index a nil value - Crash

![image](https://user-images.githubusercontent.com/125611249/219494168-bbcb0e59-95b6-434c-beb5-f40e4837fb96.png)

**Comment by odqahn** [comment]
I'm having the same issue, it's super random. Not sure where it's coming from. Any idea how to troubleshoot this?

**Comment by odqahn** [comment]
So, here's what I got on a private server:

<img width="692" alt="Screenshot 2023-03-04 at 16 42 49" src="https://user-images.githubusercontent.com/26545834/222984174-b593697f-93d5-4aa8-bf87-30cbac4ca8a4.png">

What I did is try to update to 1.1, the release zip file on GitHub contains the version 1.10b it seems. After getting the sources from main branch, I try again and got the same result.

I kinda of fixed by checking that is not null. It feels kinda dirty but couldn't find another way.

I added a function isnull function, in case other needed some check later on and did a step before calling 		gPacketHandlers.HandleIncomingPacket(e);

Here's what is looks like in simploelog.lua:
`local function isnull(s)
    return s == nil or s == ''
end`

and a bit later
`if not isnull('packet_in') then
	ashita.events.register('packet_in', 'packet_in_cb', function (e)
		gPacketHandlers.HandleIncomingPacket(e);
	end);
end`

This gave me far more stable results in the last gaming session.
